version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"  # Map container port 80 to host port 80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  default:
    driver: bridge

